apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: orders-api
        image: container-registry.br-se1.magalu.cloud/lab-registry/orders-api:10b70bfd52f9bb784c62838cd6b493c99875f88a
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api
spec:
  type: LoadBalancer
  selector:
    app: orders-api
  ports:
  - port: 8000
    targetPort: 8000
