name: Deploy

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install fastapi "scalar-fastapi>=1.8.2" uvicorn pytest httpx
      - run: pytest

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login no registry
        run: |
          REGISTRY_HOST=$(echo "${{ secrets.MGC_REGISTRY_NAME }}" | cut -d'/' -f1)
          echo "${{ secrets.MGC_REGISTRY_PASSWORD }}" | docker login https://$REGISTRY_HOST \
            -u "${{ secrets.MGC_REGISTRY_USER }}" --password-stdin

      - name: Build e push da imagem
        run: |
          docker build -t ${{ secrets.MGC_REGISTRY_NAME }}/orders-api:${{ github.sha }} .
          docker push ${{ secrets.MGC_REGISTRY_NAME }}/orders-api:${{ github.sha }}

      - name: Configurar kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.MGC_KUBECONFIG }}" > ~/.kube/config

      - name: Deploy no Kubernetes
        run: |
          # 1. Atualiza a imagem diretamente no cluster sem precisar recriar o arquivo YAML estático
          export IMAGE="${{ secrets.MGC_REGISTRY_NAME }}/orders-api:${{ github.sha }}"
          
          # 2. Verifica se o deployment já existe, se não existir, aplica o manifesto base
          kubectl get deployment orders-api || kubectl apply -f k8s/app.yaml --validate=false
          
          # 3. Força a atualização da imagem e aguarda o rollout estabilizar
          kubectl set image deployment/orders-api orders-api=$IMAGE
          kubectl rollout restart deployment/orders-api
          kubectl rollout status deployment/orders-api --timeout=180s
